# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('com.github.veqryn', 'cidr-ip-trie', '1.0.1')
require_jar('org.logstash.filters', 'logstash-filter-cidr', '3.1.6')
